### ISSUE TITLE
Unable to place charcoal pile

### ISSUE THREAD

**Issue by Kranfield** [alcatrazEscapee/tinkers-forging#17] opened 2019-01-29 20:10 UTC
Hello there,
as the title say, i can't make any charcoal pile, and the brick furnace included in the mod isn't heating ingots with any fuel (coal, lava, charcoal, wood...)
I'm using many mods, maybe the problem come from one of them.
In fact, i'm not seeing any indication of heat on the ingots.
Can you help me to solve this problem ?
Thanks a lot, your mod seems awesome !

**Comment by alcatrazEscapee** [comment] 2019-01-29 20:38
This is way too vague for me to give you any help. What specifically are you trying to do, and what is not happening / working?

**Comment by Kranfield** [comment] 2019-01-29 20:42
when i try to heat the ingots in the Brick Forge (with any fuel), it doesn't work, the forge doesn't heat anything (nothing happen, the forge stay 'cold'). And when i try to put a pile of charcoal on the ground, nothing happen, there is no charcoal on the ground.
So i can't heat the ingots, and i can't use the anvil because the ingots are not hot enough
Sorry for my weird english, i'm not a native :)

**Comment by Kranfield** [comment] 2019-01-29 20:50
![image](https://user-images.githubusercontent.com/47158268/51939416-b1f14800-240f-11e9-8f2e-294f5aed01f4.png)
here is an exemple of what happen in game, as you can see, the forge isn't working


![image](https://user-images.githubusercontent.com/47158268/51939296-68086200-240f-11e9-8bb2-86aa847939c4.png)
here you can see the mods i'm currently using

**Comment by alcatrazEscapee** [comment] 2019-01-29 20:55
Right click the forge with a flint + steel to light it.

**Comment by alcatrazEscapee** [comment] 2019-01-29 20:57
I don't know if another mod might be interfering with charcoal placement. It should be able to right-click place on any full block. If you identify a specific mod that causes this problem, or it is happening in with only Tinker's Forging present, then I can look into that.

**Comment by Kranfield** [comment] 2019-01-29 21:01
Ok, so the forge is working, i missed that step. The charcoal isn't working. I tried with only tinker's forging and tinker construct (+JEI, and base metal) and it doesn't work yet on my game.

**Comment by alcatrazEscapee** [comment] 2019-01-29 21:12
I can't reproduce this. Only thing I can think of is if somehow the ore name "charcoal" was removed from the charcoal item. (AlcatrazCore -> Config -> showDebugTooltips -> Hover over charcoal and look at Ore Dictionary Names)

**Comment by alcatrazEscapee** [comment] 2019-03-22 01:40
Closing since I can't confirm there is anything wrong.

**Closed as completed by alcatrazEscapee** 2019-03-22 01:40 UTC
Labels: question
