### ISSUE TITLE
metals cool down in server spigot! 

### ISSUE THREAD

**Issue by Neoowiz** [alcatrazEscapee/tinkers-forging#57] opened 2020-11-06 12:36 UTC
Hello metals cool down if taken from the oven instantly on the server.  Config did not change checked in single-player game everything is in order, what should I do?

I looked all your github but did not find an answer.  Spigot + forge server, just tell me should I keep fighting or delete your mod?
@alcatrazEscapee

**Comment by alcatrazEscapee** [comment] 2020-12-07 15:09
Duplicate of #30

**Closed as completed by alcatrazEscapee** 2020-12-07 15:09 UTC
Labels: duplicate
